# Generated by Django 4.2.15 on 2024-09-21 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_customersenrolledoncourse'),
        ('checkout', '0003_customersenrolledoncourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.customersenrolledoncourse')),
                ('workout_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.workoutprogram')),
            ],
        ),
    ]
