# Generated by Django 4.2.15 on 2024-09-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='testing', max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(default='Testing')),
            ],
        ),
        migrations.CreateModel(
            name='ContactFormRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
