# Generated by Django 4.2.15 on 2024-09-18 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_workoutprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersEnrolledOnCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wo_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.workoutprogram')),
            ],
        ),
    ]
